#!/bin/bash

#0 crear la carpeta mongo.pid
    
    mkdir /var/run/mongodb

 
#1 -- recordar de borrar el archivo mongod.bim (mirar logs)

    mongod --config /etc/conf/db3/mongod.conf &  
    
    mongod --config /etc/conf/db2/mongod.conf &
 
    mongod --config /etc/conf/db1/mongod.conf &

 #2 -- esperamos un poco a que se creen los 3 servidores 

    sleep 10  

 #  creamos las conecciones pertinentes
	
    # creamos una config para agregar directamente las instancias del replcia set
 
    cfg="{
        _id: 'set',
	members: [
        {_id: 1, host: 'localhost:27002'},
        {_id: 2, host: 'localhost:27001'},
        {_id: 2, host: 'localhost:27000'}
       ] 
    
    }"	
    
    mongo --port 27002 --eval "JSON.stringify(db.adminCommand({'replSetInitiate' : $cfg}))"
    sleep 5

    mongo --port 27002	
    # activamos el primary node
    cat

    # mongodb://localhost:27002,localhost:27001,localhost:27000?replicaSet=rsDBlandIT 


